version: '3.9'

services:
  mysql:
    image: mysql:latest
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=gastrozoom
    volumes:
      - data:/var/lib/mysql
    restart: always

volumes:
  data: